info:
  app:
    name: neo4j-service
    description: Neo4j service module

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    renovation.neo4j.service: DEBUG

spring:
  application:
    name: ${info.app.name}

  docker:
    compose:
      lifecycle-management: start_and_stop
      file: docker-compose.yml

  neo4j:
    uri: bolt://${NEO4J_HOST:localhost}:${NEO4J_PORT:7687}
    authentication:
      username: neo4j
      password: password
