global:
  parentChartName: renovation

postgres:
  enabled: true
  name: postgres
  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent
  db: renovation
  schema: backend
  user: postgres # todo: secret
  password: postgres1 # todo: secret
  service:
    type: NodePort
    port: 5432
    nodePort: 30432

redis:
  enabled: true
  name: redis
  image:
    repository: redis
    tag: 7.2.3-alpine
    pullPolicy: IfNotPresent

  host: redis # todo: not used
  port: 6379  # todo: not used
  password: redispass
  service:
    type: NodePort
    port: 6379
    nodePort: 30379

backend:
  enabled: true
  name: backend-service
  image:
    repository: koresmosto/renovation-backend
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: NodePort
    port: 8080
    nodePort: 30080
