#!/usr/bin/env bash
#
# Created under not commercial project "Renovation"
#
# Copyright 2021-2026
#

# PreToolUse hook: warn when editing generated / derived artifact paths.
# Advisory only — always exits 0 so nothing is blocked.

set -eu

if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

payload=$(cat || true)
[ -z "${payload}" ] && exit 0

file_path=$(printf '%s' "${payload}" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)
[ -z "${file_path}" ] && exit 0

case "${file_path}" in
  */build/*|*/dist/*|*/node_modules/*|*/.gradle/*|*/out/*|*/target/*|*/generated/*|*/.idea/*)
    printf '\033[33m[renovation-hook]\033[0m refusing to edit derived artifact: %s\n' "${file_path}" >&2
    printf '  These paths are regenerated by Gradle/npm. Edit the source instead.\n' >&2
    ;;
esac

exit 0
