{{- $ctx := dict "Values" .Values "Release" .Release "Chart" .Chart "containerPort" 27017 }}
{{ include "ca.deployment" $ctx }}
          volumeMounts:
            - name: {{ .Values.name }}-initdb-scripts
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: {{ .Values.name }}-initdb-scripts
          configMap:
            name: {{ .Values.name }}-initdb-scripts
