apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-initdb-scripts
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
data:
{{ (.Files.Glob "files/init/*").AsConfig | indent 2 }}
