apiVersion: v2
name: mongodb-chart
description: mongodb subchart
icon: https://upload.wikimedia.org/wikipedia/commons/f/f6/Icon_Arrow_Right_256x256.png
appVersion: 0.1.0
version: 0.1.0

dependencies:
  - name: mongodb
    version: 16.5.43
    repository: https://charts.bitnami.com/bitnami
    alias: mongodb
