route:
  receiver: renovation-alertmanager
  repeat_interval: 1m
receivers:
  - name: 'renovation-alertmanager'
    telegram_configs:
      - bot_token: ${TELEGRAM_BOT_TOKEN}
        api_url: https://api.telegram.org
        chat_id: ${TELEGRAM_CHAT_ID}
        parse_mode: ''
#    email_configs:
#      - to: 'tutorial.inbox@gmail.com'
#        from: 'tutorial.outbox@gmail.com'
#        smarthost: 'smtp.gmail.com:587'
#        auth_username: 'username'
#        auth_password: 'password'
