apiVersion: v1
kind: ConfigMap
metadata:
  name: extsecrets-configmap
  namespace: security
data:
  clustersecretstore.yaml: |
    apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: vault-backend
    spec:
      provider:
        vault:
          server: "http://renovation-vault.security.svc.cluster.local:8200"
          path: "secret"
          version: "v2"
          auth:
            kubernetes:
              mountPath: "kubernetes"
              role: "internal-app"
              serviceAccountRef:
                name: internal-app
                namespace: security
    ---
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: renovation-external-secret
      namespace: security
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: vault-backend
      target:
        name: renovation-secret2   # will be created as a Kubernetes Secret
        creationPolicy: Owner
      dataFrom:
        - extract:
            key: secret/data/renovation/secrets #todo: vars
---
