#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2022
#
version: '3.7'

services:
  renovation-postgres:
    image: postgres:14.2
    restart: always
    container_name: "renovation-postgres"
    ports:
      - "${POSTGRES_LOCALHOST_REDIRECT_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "./backend/src/main/resources/docker/postgres/db-init-scripts:/docker-entrypoint-initdb.d"
    networks:
      - renovation-network

  renovation-redis:
    image: redis:7.0.0-alpine
    container_name: renovation-redis
    restart: always
    ports:
      - ${REDIS_LOCALHOST_REDIRECT_PORT}:6379
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 256mb
    #    command: redis-server --include /usr/local/etc/redis/redis.conf # This redis.conf can be used
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    #    volumes:
    #      - ./backend/src/main/resources/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - renovation-network

  renovation-mongo:
    image: mongo:5.0.6
    container_name: renovation-mongo
    restart: always
    ports:
      - ${MONGO_LOCALHOST_REDIRECT_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./info/src/main/resources/db/migration/mongo/init/:/docker-entrypoint-initdb.d:ro
    networks:
      - renovation-network

  renovation-keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    restart: always
    container_name: renovation-keycloak
    command: [
      "-Dkeycloak.migration.action=import",
      "-Dkeycloak.migration.provider=singleFile",
      "-Dkeycloak.migration.file=/opt/keycloak/data/import/renovation-realm.json",
      "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING",
      "start-dev"
    ]
    volumes:
      - ./aux/keycloak-config:/opt/keycloak/data/import
#      - ./aux/ex:/opt/keycloak/data/export
#    depends_on:
#      - renovation-postgres
    ports:
      - ${KEYCLOAK_LOCALHOST_REDIRECT_PORT}:8080
    environment:
#      DB_VENDOR: POSTGRES
#      DB_ADDR: "renovation-postgres"
#      DB_DATABASE: ${POSTGRES_DB}
#      DB_SCHEMA: ${POSTGRES_DB_SCHEMA}
#      DB_USER: ${POSTGRES_USERNAME}
#      DB_PASSWORD: ${POSTGRES_PASSWORD}

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

  renovation-backend:
    image: koresmosto/renovation-backend
    build:
      context: ./backend
    restart: always
    container_name: renovation-backend
    depends_on:
      - renovation-postgres
      - renovation-redis
      - renovation-keycloak
    ports:
      - ${BACKEND_SERVER_REDIRECT_PORT}:8080
    environment:
      POSTGRES_DB_URL: "jdbc:postgresql://renovation-postgres:5432/${POSTGRES_DB}?currentSchema=renovation"
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      INFO_SERVICE_URL: ${INFO_SERVICE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
    networks:
      - renovation-network

  renovation-info:
    image: koresmosto/renovation-info
    build:
      context: ./info
    restart: always
    container_name: renovation-info
    depends_on:
      - renovation-mongo
    ports:
      - ${INFO_SERVER_REDIRECT_PORT}:9090
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
    networks:
      - renovation-network

  renovation-frontend-info:
    image: koresmosto/renovation-frontend-info
    build:
      context: ./frontend-info
    restart: always
    container_name: renovation-frontend-info
    depends_on:
      - renovation-info
    ports: #Think of volume for directory
      - ${FRONTEND_INFO_SERVER_REDIRECT_PORT}:8080
    environment:
      VUE_APP_INFO_GRAPHQL_URL: ${VUE_APP_INFO_GRAPHQL_URL}
      VUE_APP_BACKEND_API_URL: ${VUE_APP_BACKEND_API_URL}
    networks:
      - renovation-network

networks:
  renovation-network:
