#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2021
#
version: '3.7'

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "./backend/src/main/resources/db-init-scripts:/docker-entrypoint-initdb.d"
    ports:
      - "${POSTGRES_PORT}:5432"
