#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2022
#
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: koresmosto/renovation-backend:latest
          imagePullPolicy: Never
          env:
            - name: POSTGRES_DB_URL
              value: "jdbc:postgresql://renovation-postgres:5432/${POSTGRES_DB}?currentSchema=renovation"
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres1"
            - name: INFO_SERVICE_URL
              value: "http://info:9090/graphql"
        ports:
            - containerPort: 8080
