###
#  Created under not commercial project "Make it fine"
#
#  Copyright 2017-2021
###

FROM openjdk:21-jdk
MAINTAINER Kores Mosto <koresmosto@gmail.com>

VOLUME /tmp

COPY build/libs/gateway-0.0.1-SNAPSHOT.jar /app.jar

CMD ["java", "-jar", "/app.jar"]
