#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2023
#

apiVersion: v1
kind: Service
metadata:
  name: metrics-grafana-service
spec:
  selector:
    app: prometheus-kube-prometheus-prometheus
  type: NodePort
  ports:
    - port: 9090
