{
 "title": "renovation-event-service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "All", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "requests (API)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\", uri!=\"/actuator/health\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "consume (kafka)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_total{topic=\"event-topic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "publish (kafka)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_producer_topic_record_send_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Infrastructure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "healthcheck",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(health_component_status)", "legendFormat": "__auto" }
   ]
  }
 ]
}