#!/bin/bash

Color_Off='\033[0m'
BRed="\033[1;31m"    # Red
BGreen="\033[1;32m"  # Green
BYellow="\033[1;33m" # Yellow
BBlue="\033[1;34m"   # Blue

while read line; do
    if [ "${line:0:1}" == "*" ]; then
        continue
    fi
    commit_msg=$line
    break
done < "${1}"

regex='((^[#][0-9]{1,4}[ ]+.{1,80})|(^WIP[ ]+.{0,80}))'

if [[ ! "$commit_msg" =~ ^($regex)$ ]];then
    printf "${BRed}Bad commit.\n"
    printf "${BYellow}Commit message format must start with ${BBlue}'#<task number of project>' ${BYellow}or ${BBlue}'WIP'.\n"
    printf "${BYellow}Commit message length must be less than ${BBlue}'80' ${BYellow}characters.\n"
    printf "${BYellow}commit-msg hook failed (add --no-verify to bypass)\n"
    exit 1
fi
