#!/bin/sh

Color_Off='\033[0m'
BRed="\033[1;31m"    # Red
BGreen="\033[1;32m"  # Green
BYellow="\033[1;33m" # Yellow
BBlue="\033[1;34m"   # Blue

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
        if [ "$local_sha" = $z40 ]
        then
                # Handle delete
                :
        else
                if [ "$remote_sha" = $z40 ]
                then
                        # New branch, examine all commits
                        range="$local_sha"
                else
                        # Update to existing branch, examine new commits
                        range="$remote_sha..$local_sha"
                fi

		echo $range

                # Check for commit message
                regex='^((^[#][0-9]{1,4}\s+.{1,80})|(^WIP\s+.{0,80}))$'
                commit=`git rev-list -n 1 -E --grep $regex "$range"`
                if [ ! -n "$commit" ]
                then
                        echo >&2 "${BRed} Found $regex commit in $local_ref, not pushing"
                        exit 1
                fi
        fi
done

exit 0
