##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##

info:
  app:
    name: "renovation/webflux-server"
    description: Webflux server module of renovation project

server:
  host: ${WEBFLUX_SERVER_HOST:localhost}
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    renovation.webflux.server: DEBUG

spring:
  r2dbc:
    url: "${MYSQL_R2DBC_URL:r2dbc:mysql://localhost:3406/r2}"
    username: ${MYSQL_USER:r2user}
    password: ${MYSQL_PASSWORD:r2pass}

  flyway:
    url: "${MYSQL_URL:jdbc:mysql://localhost:3406/r2}"

#---

#spring:
#  config:
#    activate:
#      on-profile: integration-test
#  r2dbc:
#    url: r2dbc:tc:mysql:///testdb?TC_IMAGE_TAG=8
#
#  flyway:
##    url: "${MYSQL_URL:jdbc:mysql://localhost:3306/r2}"

#---
