##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##

info:
  app:
    name: "renovation/webflux-server"
    description: Webflux server module of renovation project

server:
  host: ${WEBFLUX_SERVER_HOST:localhost}
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    renovation.webflux.server: DEBUG

spring:
  r2dbc:
    url: "${POSTGRES_R2DBC_URL:r2dbc:postgresql://localhost:55312}"
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres1}

  flyway:
    url: "${POSTGRES_URL:jdbc:postgresql://localhost:5532/postgres}"
