#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2022
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB_URL: "jdbc:postgresql://postgres:5432/postgres?currentSchema=renovation"
  INFO_SERVICE_URL: "http://info:9090/graphql"