##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: simple_group_id

topic:
  simple: simple-topic
