##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##

spring:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093
    consumer:
      auto-offset-reset: earliest
      group-id: simple_group_id

topic:
  simple: simple-topic
