##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##

info:
  app:
    name: "renovation/kafka-service"
    description: Kafka-service module of renovation project

server:
  port: ${PORT:8095}

spring:
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,
