{{- $ctx := dict "Values" .Values "Release" .Release "Chart" .Chart "containerPort" 6379 }}
{{ include "ca.deployment" $ctx }}
          command:
            - redis-server
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
            - "--maxmemory"
            - "256mb"
