##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##

spring:
#  config:
#    activate:
#      on-profile: "certificate"
  security:
    oauth2:
      client:
        registration: # koresmosto account # https://www.youtube.com/watch?v=us0VjFiHogo&t=414s&ab_channel=DanVega
          github: # https
            client-id: ${HTTPS_SOCIAL_LOGIN_GITHUB_CLIENT_ID}
            client-secret: ${HTTPS_SOCIAL_LOGIN_GITHUB_CLIENT_SECRET}

          google: # https
            client-id: ${HTTPS_SOCIAL_LOGIN_GOOGLE_CLIENT_ID}
            client-secret: ${HTTPS_SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET}

server:
  ssl:
    key-store: src/main/resources/store/keystore.jks
    key-store-password: 1234567
    key-alias: localhost
    key-password: 12345
    enabled: true
  port: 8443

---

spring:
  config:
    activate:
      on-profile: "truststore"

server:
  ssl:
    key-store: src/main/resources/store/keystore.jks
    key-store-password: 1234567
    key-alias: localhost
    key-password: 12345
    enabled: true

    trust-store: src/main/resources/store/truststore.jks
    trust-store-password: 1234567
    client-auth: need
  port: 8443
