##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##

info:
  app:
    name: "renovation/gateway"
    description: Gateway module of renovation project

server:
  host: ${GATEWAY_HOST:localhost}
  port: ${PORT:8085}

logging:
  level:
    root: INFO
    renovation.gateway: DEBUG
    org.springframework.security: DEBUG
  file:
    path: ${RENOVATION_GATEWAY_LOG_FILE_PATH:/tmp/renovation-gateway}
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 5MB

management:
  server:
    port: 8086
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info, health, env, metrics, prometheus, keycloakhealth
    jmx:
      exposure:
        exclude: health
  endpoint:
    health:
      enabled: true
      show-details: always
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  observations:
    key-values:
      application: backend

keycloak:
  auth-server-url: http://${KEYCLOAK_HOSTNAME:localhost}:${KEYCLOAK_PORT:18080}

spring:
  application:
    name: ${info.app.name}

  security:
    oauth2:
      client:
        provider:
          oauth-client:
            issuer-uri: ${keycloak.auth-server-url}/realms/${KEYCLOAK_REALM:renovation-realm}
        registration:
          oauth-client:
            client-id: ${KEYCLOAK_GATEWAY_CLIENT_ID:renovation-gateway-client}
            client-secret: ${KEYCLOAK_GATEWAY_SECRET:02d5170a-053f-11ee-be56-0242ac120002}
#            scope: openid, profile, roles
#            authorization-grant-type: authorization_code
#            redirect-uri: {baseUrl}/login/oauth2/code/oauth2-demo-client #http://localhost:8085/login/oauth2/code/oauth-client
