##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2022
##

info:
  app:
    name: "renovation/gateway"
    description: Gateway module of renovation project

server:
  port: ${PORT:8085}

logging:
  level:
    root: INFO
    gateway: DEBUG
  file:
    path: ${RENOVATION_GATEWAY_LOG_FILE_PATH:/tmp/renovation-gateway}
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 5MB

spring:
  application:
    name: ${info.app.name}
#  main:
    #web-application-type: none

  security:
    oauth2:
      client:
        provider:
          oauth-client:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/realms/renovation-realm}
        registration:
          oauth-client:
            client-id: ${KEYCLOAK_CLIENT_ID:renovation-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:341b3ff9-7af0-4854-b024-63a82e7174cd}
            scope: openid, profile
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/oauth2-demo-client
