##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##

spring:
  security:
    oauth2:
      client:
        registration: # koresmosto account # https://www.youtube.com/watch?v=us0VjFiHogo&t=414s&ab_channel=DanVega
          github:
            client-id: ${SOCIAL_LOGIN_GITHUB_CLIENT_ID}
            client-secret: ${SOCIAL_LOGIN_GITHUB_CLIENT_SECRET}

          google:
            client-id: ${SOCIAL_LOGIN_GOOGLE_CLIENT_ID}
            client-secret: ${SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET}
