##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##

spring:
  security:
    oauth2:
      client:
        registration: # koresmosto account # https://www.youtube.com/watch?v=us0VjFiHogo&t=414s&ab_channel=DanVega
          github:
            client-id: ${SOCIAL_LOGIN_GITHUB_CLIENT_ID}
            client-secret: ${SOCIAL_LOGIN_GITHUB_CLIENT_SECRET}

          google:
            client-id: ${SOCIAL_LOGIN_GOOGLE_CLIENT_ID}
            client-secret: ${SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET}

---

spring:
  config:
    activate:
      on-profile: "cert"
  security:
    oauth2:
      client:
        registration: # koresmosto account # https://www.youtube.com/watch?v=us0VjFiHogo&t=414s&ab_channel=DanVega
          github: # https
            client-id: ${HTTPS_SOCIAL_LOGIN_GITHUB_CLIENT_ID}
            client-secret: ${HTTPS_SOCIAL_LOGIN_GITHUB_CLIENT_SECRET}

          google: # https
            client-id: ${HTTPS_SOCIAL_LOGIN_GOOGLE_CLIENT_ID}
            client-secret: ${HTTPS_SOCIAL_LOGIN_GOOGLE_CLIENT_SECRET}

server:
  ssl:
    key-store: src/main/resources/store/keystore.jks
    key-store-password: 1234567
    key-alias: localhost
    key-password: 12345
    enabled: true
  port: 8443
