apiVersion: v1
kind: Service
metadata:
  name: simple-serv2
spec:
  selector:
    app: simple-dep2
  clusterIP: 10.96.1.2
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080
#      nodePort: 30082
#  type: ClusterIP
#  type: NodePort
#  type: LoadBalancer
