apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ca.fullname" . }}-internal-secret
  labels:
    {{- include "ca.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.vault.token | quote }}
  unsealKey: {{ .Values.vault.unsealKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ca.secretName" . }}
  labels:
    {{- include "ca.labels" . | nindent 4 }}
type: Opaque
stringData:
  VAULT_ADDR: "http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.vault.server.service.port }}"
---
