apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-app
  labels:
    {{- include "ca.labels" . | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ca.fullname" . }}-seed-job
  labels:
    {{- include "ca.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "ca.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      volumes:
        - name: vault-token
          secret:
            secretName: {{ include "ca.fullname" . }}-internal-secret
      containers:
        - name: seed
          image: hashicorp/vault:1.20.1
          envFrom:
            - secretRef:
                name: {{ include "ca.secretName" . }}
          volumeMounts:
            - name: vault-token
              mountPath: /vault/token
              readOnly: true
          command:
            - /bin/sh
            - -ec
            - |
              echo "!!! Waiting for vault..."
              until vault status -address=${VAULT_ADDR} >/dev/null 2>&1; do
                sleep 2
              done

              export VAULT_TOKEN=$(cat /vault/token/token)

              echo "!!! Enabling KV v2..."
              vault secrets enable -path=secret kv-v2 || true

              echo "!!! Seeding KV secret..."
              # !!! remove if(s) to set kv keys
              if ! vault kv get secret/renovation/secrets >/dev/null 2>&1; then
               # postgres
                vault kv put secret/renovation/secrets \
                  "POSTGRES_USER=postgres" \
                  "POSTGRES_PASSWORD=postgres1" \
                  "POSTGRES_DB=renovation" \
                  "POSTGRES_SCHEMA=backend" \

                # redis
                vault kv patch secret/renovation/secrets \
                  "REDIS_PASSWORD=redispass" \

                # mongo
                vault kv patch secret/renovation/secrets \
                  "MONGO_INITDB_ROOT_PASSWORD=rootpass" \
                  "MONGO_PASSWORD=infopassword" \
                  "MONGO_INITDB_DATABASE=infodb" \
                  "MONGO_INITDB_ROOT_USERNAME=root" \
                  "MONGO_USERNAME=infouser" \
                  "MONGO_DB=infodb"
              else
                echo "secret/renovation/secrets already exists → skipping"
              fi

              echo "!!! Config k8s injection for vault, external-secrets"

              if ! vault auth list -format=json | grep -q '"kubernetes/":'; then
                echo "Enabling Kubernetes ath..."
                vault auth enable kubernetes
              else
                echo "Kubernetes auth already enabled → skipping"
              fi

              vault write auth/kubernetes/config kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443"

              # todo: move secret path to variable
              vault policy write internal-app - <<EOF
                path "secret/data/renovation/secrets" {
                capabilities = ["read"]
              }
              EOF

              # role: (!todo: bound_service_account_namespaces for single namespace)
              vault write auth/kubernetes/role/internal-app \
                bound_service_account_names=internal-app \
                bound_service_account_namespaces="default,db,apps,security,infra,low" \
                policies=internal-app \
                ttl=24
                #audience="https://kubernetes.default.svc.cluster.local"

              # for seed running indefinitely
              # echo "Seeding completed. Sleeping forever to keep pod alive... (!todo: uncomment next line)"
              # tail -f /dev/null

              echo "Job Competed"
