apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ca.vaultSecretName" . }}
  labels:
    {{- include "ca.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.vault.token | quote }}
  unsealKey: {{ .Values.vault.unsealKey | quote }}
