apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vault.name }}-secret
type: Opaque
stringData: #!!! todo: hide the values
{{/*! todo: https://chatgpt.com/s/t_68af56ced9c88191907ca9d592d5cdeb */}}
  token: "hvs.ELzor4mGdxJemZlqcep7glRn"
  unsealKey: "5553ed3b62cd99cb7a03b627d0bb0a1c351bfd1e135690138a2e859eef619c89"
