{{/*todo: create for multiple namespaces*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ca.fullname" . }}-unseal-sa
  labels:
    {{- include "ca.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ca.fullname" . }}-unseal-role
  labels:
    {{- include "ca.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]  # allow exec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ca.fullname" . }}-unseal-rb
  labels:
    {{- include "ca.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ca.fullname" . }}-unseal-sa
roleRef:
  kind: Role
  name: {{ include "ca.fullname" . }}-unseal-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ca.fullname" . }}-unseal-job
  labels:
    {{- include "ca.labels" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "ca.fullname" . }}-unseal-sa
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl:1.33.4
          env:
            - name: VAULT_UNSEAL_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "ca.fullname" . }}-internal-secret
                  key: unsealKey
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              alias COM="kubectl exec -n {{ .Release.Namespace }} {{ .Release.Name }}-0 -- sh -c"
              COM "vault operator unseal $VAULT_UNSEAL_KEY"
