apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: {{ .Values.global.parentChartName }}-configmap
            - secretRef:
                name: {{ .Values.global.parentChartName }}-secret
          volumeMounts:
            - name: initdb-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

      volumes:
        - name: initdb-scripts
          configMap:
            name: postgres-initdb-scripts
