apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-scripts
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
data:
  init-renovation-schema.sql: |
    CREATE SCHEMA IF NOT EXISTS {{ .Values.schema }} AUTHORIZATION postgres;
