info:
  app:
    name: influx-service
    description: Influx service module

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    renovation.influx.service: DEBUG

spring:
  application:
    name: ${info.app.name}

  docker:
    compose:
      lifecycle-management: start_and_stop
      file: docker-compose.yml

influx:
  url: http://${INFLUX_HOST:localhost}:${INFLUX_PORT:8186}
  database: ${INFLUXDB_DB:influxdb}
  username: ${INFLUXDB_USER:influxuser}
  password: ${INFLUXDB_PASSWORD:influxpass}
