apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.vault.name }}-seed-kv
  namespace: {{ .Values.vault.global.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: hashicorp/vault:1.20.1
          env:
            - name: VAULT_ADDR
              value: http://renovation-vault.security.svc.cluster.local:8200
          command:
            - /bin/sh
            - -ec
            - |
              echo "Waiting for Vault..."
              until vault status -address=${VAULT_ADDR} >/dev/null 2>&1; do
                sleep 2
              done

              export VAULT_TOKEN=$(cat /vault/token/token)

              echo "Enabling KV v2..."
              vault secrets enable -path=secret kv-v2 || true

              echo "Seeding KV secret..."
              echo "Seeding config..."
              # !!! remove if(s) to set kv keys
              if ! vault kv get secret/renovation/config >/dev/null 2>&1; then
                vault kv put secret/renovation/config \
                  "MONGO_INITDB_DATABASE=infodb" \
                  "MONGO_INITDB_ROOT_USERNAME=root" \
                  "MONGO_USERNAME=infouser" \
                  "ABC_V='abc abc 333'" \
                  "ABC_V2=abc abc 333" \
                  "MONGO_DB=infodb"
              else
                echo "secret/renovation/config already exists → skipping"
              fi

              echo "Config k8s injection"

              # export VAULT_TOKEN=hvs.ELzor4mGdxJemZlqcep7glRn && vault auth disable kubernetes

              #vault auth disable kubernetes #in case it's enabled
              #vault auth enable kubernetes #then enable

              if ! vault auth list -format=json | grep -q '"kubernetes/":'; then
                echo "Enabling Kubernetes ath..."
                vault auth enable kubernetes
              else
                echo "Kubernetes auth already enabled → skipping"
              fi

              vault write auth/kubernetes/config kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443"

              # todo: move secret path to variable
              vault policy write internal-app - <<EOF
                path "secret/renovation/config" {
                capabilities = ["read"]
              }
              EOF

              # role:
              vault write auth/kubernetes/role/internal-app \
                bound_service_account_names=internal-app \
                bound_service_account_namespaces=default,db,apps,security,infra \
                policies=internal-app \
                ttl=24 \
                audience=vault

              # for seed running indefinitely
              echo "Seeding completed. Sleeping forever to keep pod alive..."
              tail -f /dev/null
          volumeMounts:
            - name: vault-token
              mountPath: /vault/token
              readOnly: true
      volumes:
        - name: vault-token
          secret:
            secretName: {{ .Values.vault.name }}-secret
