image:
  repository: postgres
  tag: 16-alpine
  pullPolicy: IfNotPresent

#db: mydb # todo: could be deleted
#user: postgres
#password: postgres
#
#service:
#  type: NodePort
#  nodePort: 30432

postgres:
  db: ""
  user: ""
  password: ""

  service:
    type: ""
    nodePort: ""
