###
#  Created under not commercial project "Renovation"
#
#  Copyright 2017-2023
###

FROM openjdk:21-jdk
MAINTAINER Kores Mosto <koresmosto@gmail.com>

VOLUME /tmp

COPY build/libs/info-0.0.1-SNAPSHOT.jar /app.jar

CMD ["java", "-jar", "/app.jar"]
