#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2022
#
version: '3.7'

services:
  renovation_info_mongo:
    image: mongo:5.0.6
    container_name: renovation_info_mongo
    restart: always
    ports:
      - 27117:27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./src/main/resources/db/migration/mongo/init/:/docker-entrypoint-initdb.d:ro
    networks:
      - renovation_info-network

networks:
  renovation_info-network: