#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2022
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: koresmosto/renovation-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: renovation-configmap
#                  key: POSTGRES_DB_URL
                  key: POSTGRES_HA_DB_URL
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: renovation-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: renovation-secret
                  key: POSTGRES_PASSWORD
            - name: INFO_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: renovation-configmap
                  key: INFO_SERVICE_URL
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: renovation-configmap
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: renovation-configmap
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: renovation-secret
                  key: REDIS_PASSWORD
