#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2022
#
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      name: http-backend-service-port
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: LoadBalancer
