apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.master.persistence.existingClaim }}
  namespace: {{ .Values.redis.namespaceOverride }}
  annotations: # unnecessary here !!!
    helm.sh/resource-policy: keep
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: redis-master-0-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.redis.replica.persistence.existingClaim }}
  namespace: {{ .Values.redis.namespaceOverride }}
  annotations: # unnecessary here !!!
    helm.sh/resource-policy: keep
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: redis-replica-0-pv
