##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##
info:
  app:
    name: "Renovation temp"
    description: Renovation temp module for testing

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(-){faint} %clr([%15.15t]){faint} %clr(%-35.35logger{20}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    dateformat: MM/dd HH:mm
  level:
    root: INFO
    renovation.temp: DEBUG

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

server:
  port: ${PORT:8080}

spring:
  application:
    name: ${info.app.name}

---

spring:
  config:
    activate:
      on-profile: "!vault"
  autoconfigure:
    exclude: >
      org.springframework.cloud.vault.config.VaultAutoConfiguration,

---

spring:
  config:
    activate:
      on-profile: vault
    import: vault://
  cloud:
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8400}
      scheme: http
      token: ${VAULT_TOKEN:00000000-0000-0000-0000-000000000000}
      application-name: ${VAULT_APPLICATION_NAME:renovation_temp}

vaultValues:
  value1: ${value.value1:undef}
  value2: ${value.value2:undef}

---

spring:
  config:
    activate:
      on-profile: "no-security-no-vault"
  security:
    enabled: false
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,
      org.springframework.cloud.vault.config.VaultAutoConfiguration,

---

spring:
  config:
    activate:
      on-profile: "no-security"
  security:
    enabled: false
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,
