##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##
info:
  app:
    name: "Renovation temp"
    description: Renovation temp module for testing

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(-){faint} %clr([%15.15t]){faint} %clr(%-35.35logger{20}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    dateformat: MM/dd HH:mm
  level:
    root: INFO
    renovation.temp: DEBUG

server:
  port: ${PORT:8080}

spring:
  application:
    name: ${info.app.name}
  autoconfigure:
    exclude: >
      org.springframework.cloud.vault.config.VaultAutoConfiguration
