server:
  port: ${PORT:9090}

spring:
  data:
    mongodb:
      authentication-database: ${MONGO_INITDB_DATABASE:infodb}
      database: ${MONGO_DB:infodb}
      username: ${MONGO_USERNAME:infouser}
      password: ${MONGO_PASSWORD:infopassword}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}