server:
  port: ${PORT:9090}

spring:
  application:
    name: "renovation info"

  data:
    mongodb:
  #      authentication-database: ${MONGO_INITDB_DATABASE:infodb}
  #      database: ${MONGO_DB:infodb}
  #      username: ${MONGO_USERNAME:infouser}
  #      password: ${MONGO_PASSWORD:infopassword}
  #      host: ${MONGO_HOST:localhost}
  #      port: ${MONGO_PORT:27117}
      uri: ${MONGO_DB_URI:mongodb://infouser:infopassword@localhost:27117/infodb}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOSTNAME:localhost}:${KEYCLOAK_PORT:18080}/realms/renovation-realm/protocol/openid-connect/certs

      client:
        registration:
          client:
            client-id: ${KEYCLOAK_RESOURCE:renovation-client}

logging:
  level:
    root: INFO
    renovation.info: DEBUG
    org.springframework.security: DEBUG
