image:
  repository: postgres
  tag: 16-alpine
  pullPolicy: IfNotPresent

#todo: delete belove (all are read from configmap and secret)
db: ""
schema: ""
user: ""
password: ""
service:
  type: ""
  nodePort: ""
