apiVersion: v1
kind: Service
metadata:
  name: pgpool-svc
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: postgresql-ha
      port: 5432
      targetPort: postgresql-ha
      protocol: TCP
      nodePort: null
  selector:
    app: pgpool