#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2022
#
apiVersion: v1
kind: Service
metadata:
  name: frontend-info
spec:
  selector:
    app: frontend-info
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30081
  type: LoadBalancer
