#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2023
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: pgstore
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/pg/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: pgstore
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi