##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2023
##

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: "jdbc:h2:mem:renovation;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password: "sa"
    driverClassName: "org.h2.Driver"

  h2:
    console:
      enabled: true

# Disable redis healthCheck
#management:
#  health:
#    redis:
#      enabled: false
