##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2021
##
server:
  port: ${PORT:8080}

spring:
  application:
    name: renovation

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: "${POSTGRES_DB_URL:jdbc:postgresql://localhost:5532/testdb}"
    username: "${POSTGRES_USERNAME:postgres}"
    password: "${POSTGRES_PASSWORD:postgres1}"
    driverClassName: "org.postgresql.Driver"

  liquibase:
    change-log: db/liquibase/changelog.xml
