##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2022
##

iam:
  apiWork:
    username: work-test
    password: userpass
  apiWorker:
    username: worker-test
    password: adminpass
  api:
    username: all-test
    password: test
