##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2021
##

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: "jdbc:h2:mem:testdb;MODE=PostgreSQL"
    username: "sq"
    password: "password"
    driverClassName: "org.h2.Driver"

  h2:
    console:
      enabled: true
