##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2022
##
info:
  app:
    name: "Renovation backend"
    description: Renovation reporter for workers  and cutomers

server:
  port: ${PORT:8080}

spring:
  application:
    name: "renovation backend"

  //todo: consider to remove
  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect

  datasource:
    url: "${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=renovation}"
    username: "${POSTGRES_USERNAME:postgres}"
    password: "${POSTGRES_PASSWORD:postgres}"
    driverClassName: "org.postgresql.Driver"

  liquibase:
    change-log: db/liquibase/changelog.xml

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redispass}

  cache:
    redis:
      time-to-live: 1800000
      cache-null-values: false


logging:
  level:
    root: INFO
    renovation.backend: DEBUG
    org.hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info, health, env, metrics, prometheus
    jmx:
      exposure:
        exclude: health
  metrics:
    tags:
#      application: ${spring.application.name}
      application: backend
  endpoint:
    health:
      enabled: true
      show-details: always
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

info-service:
  graphql-url: "${INFO_SERVICE_URL:http://localhost:9090/graphql}"

keycloak:
  #  auth-server-url: http://${KEYCLOAK_HOSTNAME:localhost}:${KEYCLOAK_PORT:18080}/auth
  auth-server-url: http://${KEYCLOAK_HOSTNAME:localhost}:${KEYCLOAK_PORT:18080}
  realm: renovation-realm
  resource: renovation-client
  #  credentials:
  #    secret: <secret>
  public-client: true
  #  bearer-only: true
  principal-attribute: preferred_username
