##
# Created under not commercial project "Renovation"
#
# Copyright 2021-2022
##

iam:
  api-work: #same as 'apiWork'
    username: work-test
    password: userpass
  api-worker:
    username: worker-test
    password: adminpass
  api:
    username: all-test
    password: test
  #renovation-gateway-client / username: gateway-user -> password: test
