{{- $root := . }}

{{- $nsList := list }}
{{- $ns_default := $root.Release.Namespace }}

{{- range $key, $ns := $root.Values.global.namespace }}
  {{- $nsList = append $nsList $ns }}
{{- end }}
{{- $nsList = append $nsList $root.Release.Namespace }}

{{- range $ns := $nsList }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Values.global.parentChartName }}-configmap-vault
  namespace: {{ $ns }}
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "k8s-backend-role"
    vault.hashicorp.com/agent-inject-secret: "secret/renovation/config"
    vault.hashicorp.com/agent-inject-template: |
      MONGO_INITDB_DATABASE={{ "{{ with secret \"secret/renovation/config\" }}{{ .Data.data.MONGO_INITDB_DATABASE }}{{ end }}" }}
{{/*      MONGO_INITDB_ROOT_USERNAME={{ "{{ with secret \"secret/renovation/config\" }}{{ .Data.data.MONGO_INITDB_ROOT_USERNAME }}{{ end }}" }}*/}}
{{/*      MONGO_USERNAME={{ "{{ with secret \"secret/renovation/config\" }}{{ .Data.data.MONGO_USERNAME }}{{ end }}" }}*/}}
{{/*      MONGO_DB={{ "{{ with secret \"secret/renovation/config\" }}{{ .Data.data.MONGO_DB }}{{ end }}" }}*/}}
---
---
{{- end }}
