{{- $root := . }}
{{- $namespaces := list $root.Values.global.namespace.infra $root.Values.global.namespace.apps $root.Release.Namespace }}

{{- range $ns := $namespaces }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Values.global.parentChartName }}-configmap
  namespace: {{ $ns }}
data:
  POSTGRES_DB: {{ $root.Values.postgres.db | quote }}

  POSTGRES_DB_URL: "jdbc:postgresql://{{ $root.Values.postgres.name }}.{{ $root.Values.global.namespace.infra }}.svc.cluster.local:{{ $root.Values.postgres.service.port }}/renovation?currentSchema=backend"

  INFO_SERVICE_URL: "http://{{ $root.Values.info.name }}.{{ $root.Release.Namespace }}.svc.cluster.local:{{ $root.Values.info.service.port }}/graphql"

  REDIS_HOST: "{{ $root.Values.redis.name }}.{{ $root.Release.Namespace }}.svc.cluster.local"
  REDIS_PORT: {{ $root.Values.redis.service.port | quote }}

  MONGO_INITDB_DATABASE: {{ $root.Values.mongo.initdb.database | quote }}
  MONGO_INITDB_ROOT_USERNAME: {{ $root.Values.mongo.initdb.rootuser.username | quote }}

  MONGO_USERNAME: {{ $root.Values.info.mongo.username | quote }}
  MONGO_DB: {{ $root.Values.mongo.initdb.database | quote }}
  MONGO_HOST: "{{ $root.Values.mongo.name }}.{{ $root.Release.Namespace }}.svc.cluster.local"
  MONGO_PORT: {{ $root.Values.mongo.service.port | quote }}
---
{{- end }}
