apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-configmap
  namespace: {{ .Values.mongodb.namespaceOverride }}
data:
  use_auth_database.js: |
    use infodb;
{{ (.Files.Glob "resource/mongodb/init/*").AsConfig | indent 2 }}
