apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.platform }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.infra }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.apps }}
---

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.security }}
---
