apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
    POSTGRES_USER: {{ .Values.postgres.user | b64enc }}
    POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}

    REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}

    MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.initdb.rootuser.password | b64enc }}
    MONGO_PASSWORD: {{ .Values.info.mongo.password | b64enc }}
