{{- $root := . }}

{{- $nsList := list }}
{{- range $key, $ns := $root.Values.global.namespace }}
  {{- $nsList = append $nsList $ns }}
{{- end }}
{{- $nsList = append $nsList $root.Release.Namespace }}

{{- range $ns := $nsList }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.global.parentChartName }}-secret
  namespace: {{ $ns }}
type: Opaque
data:
  POSTGRES_USER: {{ $root.Values.postgresql.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ $root.Values.postgresql.auth.password | b64enc }}

  REDIS_PASSWORD: {{ $root.Values.redis.password | b64enc }}

  MONGO_INITDB_ROOT_PASSWORD: {{ $root.Values.mongo.initdb.rootuser.password | b64enc }}
  MONGO_PASSWORD: {{ $root.Values.info.mongo.password | b64enc }}
---
{{- end }}
