{{- $root := . -}}

{{- if .Values.global.secrets.enabled -}} #0

{{- range $ns := .Values.global.secrets.namespaces }} #1
apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-app
  namespace: {{ $ns }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "ca.fullname" $root }}-vault-store-{{ $ns }}
  namespace: {{ $ns }}
spec:
  provider:
    vault:
      server:  {{ $root.Values.global.secrets.vault.servicePath | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "internal-app"
          serviceAccountRef:
            name: internal-app
            namespace: {{ $ns }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ca.fullname" $root }}-vault-external-postgresql-secret
  namespace: {{ $ns }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "ca.fullname" $root }}-vault-store-{{ $ns }}
  target:
    name: extsecrets-postgresql-secret   # will be created as a Kubernetes Secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB   # key in the K8s Secret
      remoteRef:
        key: renovation/secrets # Vault path (without "secret/data/")
        property: POSTGRES_DB  # field inside that secret
    - secretKey: POSTGRES_USER
      remoteRef:
        key: renovation/secrets
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: renovation/secrets
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_SCHEMA
      remoteRef:
        key: renovation/secrets
        property: POSTGRES_SCHEMA
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ca.fullname" $root }}-vault-external-redis-secret
  namespace: {{ $ns }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "ca.fullname" $root }}-vault-store-{{ $ns }}
  target:
    name: extsecrets-redis-secret   # will be created as a Kubernetes Secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: renovation/secrets
        property: REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ca.fullname" $root }}-vault-external-mongodb-secret
  namespace: {{ $ns }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "ca.fullname" $root }}-vault-store-{{ $ns }}
  target:
    name: extsecrets-mongodb-secret   # will be created as a Kubernetes Secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_DB   # key in the K8s Secret
      remoteRef:
        key: renovation/secrets # Vault path (without "secret/data/")
        property: MONGO_DB  # field inside that secret
    - secretKey: MONGO_USERNAME
      remoteRef:
        key: renovation/secrets
        property: MONGO_USERNAME
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: renovation/secrets
        property: MONGO_PASSWORD
    - secretKey: MONGO_INITDB_DATABASE
      remoteRef:
        key: renovation/secrets
        property: MONGO_INITDB_DATABASE
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: renovation/secrets
        property: MONGO_INITDB_ROOT_USERNAME
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: renovation/secrets
        property: MONGO_INITDB_ROOT_PASSWORD
---

{{- end }} #1

{{- end }} #0
