{{- $root := . -}}

{{- if .Values.global.secrets.enabled -}}

  {{- range $ns := .Values.global.secrets.namespaces }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "ca.fullname" $root }}-vault-store
  labels:
    {{- include "ca.labels" $root | nindent 4 }}
spec:
  provider:
    vault:
      server:  {{ $root.Values.global.secrets.vault.servicePath | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "internal-app"
          serviceAccountRef:
            name: internal-app
            namespace: {{ $ns }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "ca.fullname" $root }}-vault-external-secret
  namespace: {{ $ns }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "ca.fullname" $root }}-vault-store
  target:
    name: extsecrets-secret   # will be created as a Kubernetes Secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: secret/data/renovation/secrets #todo: vars
---
{{- end }}

{{- end }}
