apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  labels:
    {{- include "ca.labels" . | nindent 4 }}
data:
  MONGO_HOST: "{{ .Values.mongodb.fullnameOverride }}.{{ .Values.mongodb.namespaceOverride }}.svc.cluster.local"
  MONGO_PORT: {{ .Values.mongodb.service.ports.mongodb | quote}}
