apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-configmap
  labels:
    {{- include "ca.labels" . | nindent 4 }}
data:
{{- range $path, $file := .Files.Glob "resources/init/*" }}
  {{ base $path }}: |
    use {{ index $.Values.mongodb.auth.databases 0 }};
{{ toString $file | indent 4 }}
{{- end }}
