apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.persistence.existingClaim }}
  namespace: {{ .Values.mongodb.namespaceOverride }}
  annotations: # unnecessary here !!!
    helm.sh/resource-policy: keep
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongodb-master-0-pv
