{{- range $ns := .Values.configMapNamespaces }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $ns }}-mongodb-configmap
  namespace: {{ $ns }}
  labels:
    {{- include "ca.labels" $ | nindent 4 }}
data:
  MONGO_HOST: "{{ $.Values.mongodb.fullnameOverride }}.{{ $.Release.Namespace }}.svc.cluster.local"
  MONGO_PORT: {{ $.Values.mongodb.service.ports.mongodb | quote}}
---
{{- end }}
