apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.primary.persistence.existingClaim }}
  labels:
    {{- include "ca.labels" . | nindent 4 }}
  annotations: # unnecessary here !!!
    helm.sh/resource-policy: keep
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-primary-0-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.readReplicas.persistence.existingClaim }}
  labels:
    {{- include "ca.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-replica-0-pv
