#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2023
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:5.0.6
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: renovation-configmap
                  key: MONGO_INITDB_DATABASE
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: renovation-configmap
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: renovation-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /data/db
              name: mongodb
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongo-pv-claim
        - name: initdb
          hostPath:
            path: /mnt/mongo/init
