#
#     Created under not commercial project "Renovation"
#
#     Copyright 2021-2022
#
apiVersion: v1
kind: Service
metadata:
  name: info
spec:
  selector:
    app: info
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  type: LoadBalancer
