{{/* ServiceAccount for unsealing Vault and creating ClusterSecretStore */}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: extsecrets-sa
  namespace: {{ .Values.global.namespace.security }}
---
{{/* ClusterRole for creating ClusterSecretStore */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extsecrets-eso-role
  namespace: {{ .Values.global.namespace.security }} # doesn't depends
rules:
  - apiGroups: [ "external-secrets.io" ]
    resources: [ "clustersecretstores", "externalsecrets" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
{{/* ClusterRoleBinding to bind the ClusterRole to the ServiceAccount */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extsecrets-eso-crb
  namespace: {{ .Values.global.namespace.security }}
subjects:
  - kind: ServiceAccount
    name: extsecrets-sa
    namespace: {{ .Values.global.namespace.security }}
roleRef:
  kind: ClusterRole
  name: extsecrets-eso-role
  apiGroup: rbac.authorization.k8s.io
---
{{/* Job to wait and apply ClusterSecretStore */}}
apiVersion: batch/v1
kind: Job
metadata:
  name: just-sleep-for-extsecrets
  namespace: {{ .Values.global.namespace.security }}
{{/*  annotations:*/}}
{{/*    "helm.sh/hook": post-install*/}}
{{/*    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded*/}}
spec:
  template:
    metadata:
      labels:
        job: wait-extsecrets
    spec:
      serviceAccountName: extsecrets-sa
      restartPolicy: Never
      volumes:
        - name: clustersecretstore
          configMap:
            name: extsecrets-configmap
      containers:
        - name: wait-extsecrets
          image: bitnami/kubectl:1.33.4
          volumeMounts:
            - name: clustersecretstore
              mountPath: /tmp/clustersecretstore.yaml
              subPath: clustersecretstore.yaml
          env:
            - name: VAULT_ADDR
              value: http://renovation-vault.security.svc.cluster.local:8200 #!todo: extract into var. (delete)
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              echo "sleeping ..."
              echo "---"
              echo $VAULT_ADDR
              echo "---"
              cat /tmp/clustersecretstore.yaml

              sleep 30 #!todo: wait until vault is fine

              echo "Creating ClusterSecretStore..."
              # ! todo make post-install
              kubectl apply -f /tmp/clustersecretstore.yaml

{{/*              tail -f /dev/null*/}}
              echo "completed. Sleeping forever to keep pod alive..."
