apiVersion: v1
kind: ConfigMap
metadata:
  name: extsecrets-configmap
  namespace: security
data:
  clustersecretstore.yaml: |
    apiVersion: external-secrets.io/v1
    kind: ClusterSecretStore
    metadata:
      name: vault-backend
    spec:
      provider:
        vault:
          server: "http://renovation-vault.security.svc.cluster.local:8200"
          path: "secret"
          version: "v2"
          auth:
            kubernetes:
              mountPath: "kubernetes"
              role: "internal-app"
              serviceAccountRef:
                name: internal-app
                namespace: security
    ---
    {{- $root := . }}

    {{- $nsList := list }}
    {{- range $key, $ns := $root.Values.global.namespace }}
      {{- $nsList = append $nsList $ns }}
    {{- end }}
    {{- $nsList = append $nsList $root.Release.Namespace }}

    {{- range $ns := $nsList }}
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: renovation-external-secret
      namespace: {{ $ns }}
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: ClusterSecretStore
        name: vault-backend
      target:
        name: {{ $root.Values.global.parentChartName }}-vault-secret   # will be created as a Kubernetes Secret
        creationPolicy: Owner
      dataFrom:
        - extract:
            key: secret/data/renovation/secrets #todo: vars
    ---
    {{- end }}
