info:
  app:
    name: batch-service
    description: Batch service module

server:
  port: ${PORT:8080}

management:
  endpoints:
    enabled-by-default: true #todo: fix
    web:
      exposure:
        include: info, health, env, metrics
    jmx:
      exposure:
        exclude: health
  endpoint:
    health:
      enabled: true #todo: fix
      show-details: always
    metrics:
      access: unrestricted
  info:
    env:
      enabled: true
  health:
    livenessstate: #todo: fix
      enabled: true
    readinessstate:
      enabled: true
  observations:
    key-values:
      application: ${info.app.name}

logging:
  level:
    root: INFO
    renovation.batch.service: DEBUG

spring:
  application:
    name: ${info.app.name}

  docker:
    compose:
      lifecycle-management: start_and_stop
      file: docker-compose.yml

  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  datasource:
    url: "${POSTGRES_DB_URL:jdbc:postgresql://localhost:5532/postgres?currentSchema=renovation-batch}"
    username: "${POSTGRES_USERNAME:postgres}"
    password: "${POSTGRES_PASSWORD:postgres1}"
    driverClassName: "org.postgresql.Driver"
    hikari:
      max-lifetime: 5000
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 12

  flyway:
    connect-retries: 5
    connect-retries-interval: 3s
