kind: Namespace
apiVersion: v1
metadata:
  name: app2
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: app2
  namespace: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: kicbase/echo-server:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MESSAGE
              value: hello from app2
---
kind: Service
apiVersion: v1
metadata:
  name: app2
  namespace: app2
spec:
  selector:
    app: app2
  ports:
    - port: 80
      targetPort: 8000
