# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI build, test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          gradle-version: 7.5.1
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: gradle detekt

      - run: gradle test
      - run: gradle integrationTest

      - run: gradle assemble

      - run: gradle :frontend:npmInstall
      - run: gradle :frontend:npmBuild

      - run: gradle :frontend-info:npmInstall
      - run: gradle :frontend-info:npmBuild

      - run: gradle :ng-part:npmInstall
      - run: gradle :ng-part:npmLint

      - run: gradle :node-server:npmInstall
      - run: gradle :node-server:npmLint
      - run: gradle :node-server:npmTest

  ng_part_e2eTest:
    needs: [ build ]
    uses: makeitfine-org/renovation/.github/workflows/reusable_project_assemble.yaml@develop
    with:
      command_line_task: "gradle :ng-part:npmE2eTest"

  gateway_e2eTest:
    needs: [ build ]
    uses: makeitfine-org/renovation/.github/workflows/reusable_project_assemble.yaml@develop
    with:
      command_line_task: "gradle :gateway:e2eTest"

  info_e2eTest:
    needs: [ build ]
    uses: makeitfine-org/renovation/.github/workflows/reusable_project_assemble.yaml@develop
    with:
      command_line_task: "gradle :info:e2eTest"

  api_test_e2eTest:
    needs: [ build ]
    uses: makeitfine-org/renovation/.github/workflows/reusable_project_assemble.yaml@develop
    with:
      command_line_task: "gradle :api-test:e2eTest"
      timeout-minutes: 12
