# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI build, test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  schedule:
    - cron: "45 23 * * 4"

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 18
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - run: ./gradlew buildAll

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

#  api_test_e2eTest:
#    needs: [ build ]
#    uses: makeitfine-org/renovation/.github/workflows/reusable_project_assemble.yaml@develop
#    with:
#      command_line_task: "gradle :api-test:e2eTest"
#      timeout-minutes: 12
